services:

  postgres:
    container_name: radio_db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  web:
    container_name: django_backend
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - postgres
      - redis
  
  celery-beat:
    command: celery -A radioAPI beat --loglevel=info
    env_file:
      - ./.env
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis


  celery-worker:
    build:
      context: .
    command: celery -A radioAPI worker --concurrency=4 --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  flower:
    build:
      context: .
    command: celery -A radioAPI --broker="${CELERY_BROKER}" flower --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5557:5555
    depends_on:
      - redis
      - postgres
      - celery-worker

  redis:
    image: redis:7-alpine

volumes:
  database-data:
