# Generated by Django 4.1.4 on 2023-02-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="state",
            name="state_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
