# Generated by Django 4.1.4 on 2023-02-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_genre_alter_state_state_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("frequency", models.JSONField()),
                ("contacts", models.JSONField()),
                ("socials", models.JSONField()),
                (
                    "city",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="API.city"),
                ),
                ("genres", models.ManyToManyField(to="API.genre")),
            ],
        ),
    ]
