# Generated by Django 4.1.4 on 2023-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0003_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="link",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
