# Generated by Django 4.1.4 on 2023-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0004_country_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_parsed",
            field=models.BooleanField(default=False),
        ),
    ]
