# Generated by Django 4.1.4 on 2023-06-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_country_is_parsed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.TextField()),
                ("is_parsed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="country",
            name="is_parsed",
        ),
    ]
