# Generated by Django 4.2.8 on 2023-12-22 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0006_links_remove_country_is_parsed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="link",
        ),
    ]
