# Generated by Django 4.2.8 on 2023-12-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0007_remove_country_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="state_name",
            field=models.CharField(max_length=100),
        ),
    ]
