# Generated by Django 4.1.4 on 2023-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_remove_station_genres_station_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="genres",
        ),
        migrations.AddField(
            model_name="station",
            name="genres",
            field=models.ManyToManyField(to="API.genre"),
        ),
    ]
