# Generated by Django 4.1.6 on 2023-12-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0008_alter_state_state_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="country",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="API.country"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="state",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="API.state"),
            preserve_default=False,
        ),
    ]
