# Generated by Django 4.1.4 on 2023-07-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_remove_station_genres_station_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="country",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="API.country"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="state",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="API.state"),
            preserve_default=False,
        ),
    ]
