# Generated by Django 4.2.8 on 2023-12-27 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0009_station_country_station_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="country",
        ),
        migrations.RemoveField(
            model_name="station",
            name="state",
        ),
    ]
