# Generated by Django 4.1.6 on 2023-07-14 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0009_station_country_station_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="country",
        ),
        migrations.RemoveField(
            model_name="station",
            name="state",
        ),
    ]
