# Generated by Django 4.2.8 on 2024-01-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("API", "0010_remove_station_country_remove_station_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="country",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="API.country"),
        ),
        migrations.AddField(
            model_name="station",
            name="state",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="API.state"),
        ),
    ]
